app/models.py
from . import db
from flask.ext.login import UserMixin
from werkzeug.security import generate_password_hash, check_password_hash
from datetime import datetime


class Catergory(db.Model):

	__tablename__ = 'catergory'

	id = db.Column(db.Integer, primary_key=True)
	name  = db.Column(db.String(20))
	posts = db.relationship('Post', backref='catergory', lazy='dynamic')


	def __repr__(self):
		return '<catergory:%r' % self.name




class Post(db.Model):

	__tablename__ = 'posts'

	id = db.Column(db.Integer, primary_key=True)
	title = db.Column(db.String(80))
	content = db.Column(db.Text)
	pub_date = db.Column(db.DateTime, default=datetime.utcnow)
	catergory_id = db.Column(db.Integer, db.ForeignKey('catergory.id'))


	def __repr__(self):
		return '<tilele:%r' % self.title





class User(UserMixin, db.Model):

	__tablename__ = 'users'

	id = db.Column(db.Integer, primary_key=True)
	username = db.Column(db.String(64), unique=True, nullable=False)
	password_hash = db.Column(db.String(128), nullable=False)

	def verify_password(self, password):
		return check_password_hash(self.password_hash, password)

	# def is_active(self):
		# return self.active
		# return True

	# def is_authenticated(self):
		# return True

	# def is_anonymous(self):
		# return False

	def __repr__(self):
		return '<user:%r' % self.username	

app/main/forms.py
from flask.ext.wtf import Form
from wtforms import StringField, SubmitField, TextAreaField, SelectField
from wtforms.validators import Required



class writeForm(Form):
	title = StringField('Title', validators=[Required()])
	catergory = SelectField('Catergory',  validators=[Required()])
	content = TextAreaField('Content', validators=[Required()])
	submit = SubmitField('Publish')

app/__init__.py
from flask import Flask
from flask.ext.sqlalchemy import SQLAlchemy
from flask.ext.bootstrap import Bootstrap
from flask.ext.login import LoginManager
from flask.ext.moment import Moment


from config import config

bootstrap = Bootstrap()
db = SQLAlchemy()
moment = Moment()
login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'

def create_app(config_name):
	app = Flask(__name__)
	app.config.from_object(config[config_name])
	config[config_name].init_app(app)

	bootstrap.init_app(app)
	db.init_app(app)
	moment.init_app(app)
	login_manager.init_app(app)
	from .main import main 
	app.register_blueprint(main)

	from .auth import auth 
	app.register_blueprint(auth, url_prefix='/auth')

	return app

app/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__, template_folder='templates', static_folder='static')

from . import views, forms, errors

app/main/views.py
import markdown
from flask import render_template, session, redirect, url_for, flash, request
from datetime import datetime
from flask.ext.login import login_user, logout_user, login_required
from flask import Markup

from . import main
from .forms import writeForm
from .. import db
from ..models import Catergory, Post, User
from .. import login_manager

from config import Config



def get_catergories():
	catergories = []
	for catergory in Catergory.query.all():
		post_count = Post.query.filter_by(catergory_id=catergory.id).count()
		catergories.append((catergory, post_count))
	return catergories





@login_manager.user_loader
def load_user(id):
    return User.query.get(int(id))


##view functions##    

@main.route('/')
@main.route('/page/<int:page>')
def home(page=1):
	posts = Post.query.order_by(Post.pub_date.desc()).paginate(page, Config.ITEMS_PER_PAGE, False)
	catergories = get_catergories()
	return render_template('main/home.html', posts=posts, catergories=catergories)



@main.route('/new', methods=['GET', 'POST'])
@login_required
def new():
	form = writeForm()
	catergories = get_catergories()
	form.catergory.choices = [(c[0].name, c[0].name) for c in catergories]
	if form.validate_on_submit():
		title = form.title.data
		catergory = form.catergory.data
		content = form.content.data
		content = Markup(markdown.markdown(content))
		catergory_select = Catergory.query.filter_by(name=catergory).first()
		post = Post(title=title, content=content, catergory=catergory_select)
		db.session.add(post)
		db.session.commit()
		return redirect(url_for('main.home'))
	return render_template('main/new_post.html', catergories=catergories, form=form)


@main.route('/article/<int:post_id>')
def article(post_id): 
	post = Post.query.get(post_id)
	catergories = get_catergories()
	return render_template('main/article.html', post=post, catergories=catergories)


@main.route('/<catergory_name>')
@main.route('/<catergory_name>/<int:page>')
def filter_by_catergory(catergory_name, page=1):
	catergories = get_catergories()
	catergory= Catergory.query.filter_by(name=catergory_name).first()
	posts= catergory.posts.order_by(Post.pub_date.desc()).paginate(page, Config.ITEMS_PER_PAGE, False)
	return render_template('main/catergory.html', posts=posts, catergories=catergories, catergory_name=catergory_name)


@main.route('/edit/<int:post_id>', methods=['GET', 'POST'])	
@login_required
def edit(post_id):
	post = Post.query.get_or_404(post_id)
	catergories = get_catergories()
	form = writeForm()
	form.catergory.choices = [(c[0].name, c[0].name) for c in catergories]
	if form.validate_on_submit():
		post.title = form.title.data
		post.catergory = Catergory.query.filter_by(name=form.catergory.data).first()
		post.content = form.content.data
		post.content = Markup(markdown.markdown(post.content))
		db.session.add(post)
		db.session.commit()
		return redirect(url_for('main.home'))
	form.title.data = post.title
	form.catergory.data = post.catergory
	form.content.data = post.content
	return render_template('main/new_post.html', form=form)


@main.route('/editall', methods=['GET', 'POST'])
@login_required
def editall():
	posts = Post.query.all()
	catergories = get_catergories()
	return render_template('main/editall.html', posts=posts, catergories=catergories)


@main.route('/addcatergory', methods=['POST'])
@login_required
def add_catergory():
	if request.method == 'POST':
		name = request.form['catergory']
		if not Catergory.query.filter_by(name=name).first():			
			catergory = Catergory(name=name)
			db.session.add(catergory)
			db.session.commit()
			flash("Successfully add a new catergory.")
		else:
			flash("The catergory has existed.")
		return redirect(url_for('main.editall'))


@main.route('/deletecatergory', methods=['POST'])
@login_required
def delete_catergory():
	if request.method == 'POST':
		list_ = request.form.getlist('checklist')
		if not list_:
			flash("You need to select at least one catergory.")
		else:
			for catergory in list_:
				db.session.delete(Catergory.query.filter_by(name=catergory).first())
				db.session.commit()
			flash("Successfully delete a catergory.")
	return redirect(url_for('main.editall'))


@main.route('/deletepost', methods=['POST'])
@login_required
def delete_post():
	if request.method == 'POST':
		list_ = request.form.getlist('postlist')
		if not list_:
			flash("You need to select at least one post.")
		else:
			for post in list_:
				db.session.delete(Post.query.filter_by(title=post).first())
				db.session.commit()
			flash('Successfully delete a post.')
	return redirect(url_for('main.editall'))

app/templates/layout.html
{% extends "bootstrap/base.html" %}



{% block title %}Leo's Blog{% endblock title%}
{% block head %}
{{super()}}
<link href="{{url_for('static', filename='blog.css')}}" rel="stylesheet">
<link rel="shortcut icon" href="{{url_for('static', filename='favicon.ico')}}">
{% endblock head%}

{% block navbar %}
  <nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{{url_for('main.home')}}">Leo's Blog</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="dropdown">
           <a href="{{url_for('main.home')}}" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Articles <span class="caret"></span></a>
           <ul class="dropdown-menu">
             {% for catergory in catergories %}
               <li><a href="{{url_for('main.filter_by_catergory', catergory_name=catergory[0].name)}}">{{catergory[0].name}} </a></li>
             {% endfor %}
           </ul>
         </li>
        {% if current_user.is_authenticated %}
        <li><a href="{{url_for('main.new')}}">New post</a></li>
        <li><a href="{{url_for('main.editall')}}">Edit</a></li>
        {% endif %}
      </ul>
      <ul class="nav navbar-nav navbar-right">
      {% if not current_user.is_authenticated %}
        <li><a href="{{url_for('auth.login')}}">Login</a></li>
      {% else %}
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown"><img src="http://www.gravatar.com/avatar/816d106f567b61780c50a805ceed3f0f?s=18">{{current_user.username}}<b class="caret"></b></a>
        <ul class="dropdown-menu">
            <li><a href="{{ url_for('auth.logout') }}">Logout</a></li>
        </ul>
        </li>
      {% endif %}
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
{% endblock navbar %}


{% block content %}
<div class="container">

{%with messages=get_flashed_messages()%}
  {% for message in messages %}
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    {{message}}
  </div>
  {% endfor %}
{% endwith %}


{% block post%}
{% endblock post%}
</div>

<footer class="blog-footer ">
  <p>&copy; Copyright 2011-{{ moment().format('YYYY') }} <a href="mailto:{{'rookiebulls@gmail.com'}}">Email: rookiebulls@gmail.com</a></p>
  <p>
    <a href="#">Back to top</a>
  </p>
</footer>
{% endblock content %}



{% block scripts %}
  {{super()}}
  {{ moment.include_jquery() }}
  {{ moment.include_moment() }}
  {{ moment.lang("en") }}
  <script type="text/javascript">
$('.blog-footer').css('margin-top',$(document).height() - ($('.navbar').height() + $('.container').height()+80));
</script>
{% endblock scripts %}

app/templates/main/_catergories.html
<div class="sidebar-module">
<h4>Catergories</h4>
	<ol class="list-unstyled">
	{% for catergory in catergories %}
	<li><a href="{{url_for('main.filter_by_catergory', catergory_name=catergory[0].name)}}">{{catergory[0].name}} <span class="badge">{{catergory[1]}}</span></a></li>
	{% endfor %}

	</ol>
</div>

app/templates/main/_post_header.html
<div class="blog-post">
<div class="page-header">

  	{% if current_user.is_authenticated %}
	<a class="btn btn-primary pull-right" href="{{url_for('main.edit', post_id=post.id)}}">Edit</a>

	{% endif %}
	<a href="{{url_for('main.article', post_id=post.id)}}"><h2 class="blog-post-title">{{post.title}}</h2></a>

	<p class="blog-post-meta">Posted by <a href="{{url_for('main.editall')}}">{%if current_user.is_authenticated%}{{current_user.username}}{%else%}rookiebulls{%endif%}</a> on {{moment(post.pub_date).format('ll')}} under <a href="{{url_for('main.filter_by_catergory', catergory_name=post.catergory.name)}}">{{post.catergory.name}}</a></p>
	<p>{{post.content[:100] | striptags}}...<a href="{{url_for('main.article', post_id=post.id)}}">more</a></p>
  </div>
</div>

app/templates/main/_posts.html
{% for post in posts.items %}
{% include "main/_post_header.html" %}
{% endfor %}

app/templates/main/_prev_next.html
<nav>
	<ul class="pager">
		{% if not posts.has_prev %}
		<li class="disabled"><a href="#">Previous</a></li>
		{% else %}
		<li><a href="{{url_for('main.home', page=posts.prev_num)}}">Previous</a></li>
		{% endif %}
		{% if not posts.has_next %}
		<li class="disabled pull-right"><a href="#">Next</a></li>
		{% else %}
		<li class="pull-right"><a href="{{url_for('main.home', page=posts.next_num)}}">Next</a></li>
		{% endif %}
	</ul>
</nav>

app/templates/main/_prev_next_catergory.html
<nav>
	<ul class="pager">
		{% if not posts.has_prev %}
		<li class="disabled"><a href="#">Previous</a></li>
		{% else %}
		<li><a href="{{url_for('main.filter_by_catergory', catergory_name=catergory_name, page=posts.prev_num)}}">Previous</a></li>
		{% endif %}
		{% if not posts.has_next %}
		<li class="disabled pull-right"><a href="#">Next</a></li>
		{% else %}
		<li class="pull-right"><a href="{{url_for('main.filter_by_catergory', catergory_name=catergory_name, page=posts.next_num)}}">Next</a></li>
		{% endif %}
	</ul>
</nav>

app/templates/main/article.html
{% extends "layout.html" %}
{% block post %}
<div class="container">
    <div class="row">
    <div class="col-sm-8 blog-content">
	
	{% if post %}
	{% if current_user.is_authenticated%}
	<a href="{{url_for('main.edit', post_id=post.id)}}"><span class="glyphicon glyphicon-edit pull-right">Edit</span></a>
	{% endif %}
	<h2> {{post.title}}</h2>
	<span class="label label-default">{{moment(post.pub_date).format('ll')}}</span>
	<span class="label label-info">{{post.catergory.name}}</span>
    
	<hr>
      {{post.content|safe}}
    {% else %}}
    <h2>Oops, nothing here!</h2>
    {% endif %}
      

	</div>
	<div class="col-sm-3 col-sm-offset-1 blog-sidebar">
	  
	    {% include "main/_catergories.html"%}
	  

	  </div><!-- /.blog-sidebar -->
	</div>


	


</div>


    

{% endblock%}

app/templates/main/catergory.html
{% extends "layout.html"%}


{% block post %}

<div class="container">

      <div class="row">

        <div class="col-sm-8 blog-main">
          {% include "main/_posts.html" %}

          {% include "main/_prev_next_catergory.html"%}

        </div>


          <div class="col-sm-3 col-sm-offset-1 blog-sidebar">
            
              {% include "main/_catergories.html"%}
            

            </div><!-- /.blog-sidebar -->


     </div>


       
     </div><!-- /.row -->

   </div><!-- /.container -->


{% endblock %}
 

app/templates/main/editall.html
{% extends "layout.html"%}

{% block post %}
<div class="container">

<div class="page-header">
<div class="media">
  <div class="media-left media-top">
    <img class="media-object" src="http://www.gravatar.com/avatar/816d106f567b61780c50a805ceed3f0f?s=100" alt="about">
  </div>
  <div class="media-body">
     <h4 class="media-heading">{{current_user.username}}</h4>
   </div>
</div>
</div>
<h3>Edit catergory</h3>
<div class="panel panel-default">
<div class="panel-body">
<a class="btn btn-primary btn-xs pull-right" data-toggle="modal" data-target="#myModal">New</a>
<form method="POST" action="{{url_for('main.delete_catergory')}}">

{% for catergory in catergories %}
<div class="checkbox">
  <label>
    <input type="checkbox" value="{{catergory[0].name}}" name="checklist">
    {{catergory[0].name}}
  </label>
</div>
{% endfor %}

<button class="btn btn-danger btn-xs" type="submit">Delete</button>
</form>
</div>
</div>

<h3>Edit articles</h3>
<div class="panel panel-default">
<div class="panel-body">
<form method="POST" action="{{url_for('main.delete_post')}}">

{% for post in posts %}
{% set index=loop.index %}
<div class="checkbox">
  <label>
    <input type="checkbox" value="{{post.title}}" name="postlist">
    <span>{{index}}. </span><strong> {{post.title}} </strong>  under <a href="#">#{{post.catergory.name}}#</a>
  </label>
  <a class="btn btn-primary btn-xs pull-right" href="{{url_for('main.edit', post_id=post.id)}}">Edit</a>
  <hr>
</div>

{% endfor %}
<button class="btn btn-danger btn-xs" type="submit">Delete</button>
</form>
</div>
</div>





</div>

<div class="modal fade bs-example-modal-sm" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog modal-sm" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <h4 class="modal-title" id="myModalLabel">Add a catergory</h4>
        </div>
        <div class="modal-body">
          <form action="{{ url_for('main.add_catergory') }}" method=post>
            <div class="form-group">
              <input type="text" class="form-control" name="catergory">
            </div>                          
            <button type="submit" class="btn btn-primary">Submit</button>               
          </form>
        </div>
      </div>
     </div>
    </div>
</div>

{% endblock %}

app/templates/main/home.html
{% extends "layout.html"%}


{% block post %}

<div class="container">

      <div class="row">

        <div class="col-sm-8 blog-main">
          {% include "main/_posts.html" %}

          {% include "main/_prev_next.html"%}

        </div>


          <div class="col-sm-3 col-sm-offset-1 blog-sidebar">
            <div class="sidebar-module sidebar-module-inset">
              <div class="media">
                <div class="media-left media-top">
                    <img class="media-object" src="http://www.gravatar.com/avatar/816d106f567b61780c50a805ceed3f0f?s=64" alt="about">
                </div>
                <div class="media-body">
                   <h4 class="media-heading">Kevin Garnett</h4>
  
                 </div>
                  <p>I'm such a charming guy.
                   Mail me if you want my signature. <a href="mailto:{{'rookiebulls@gmail.com'}}">rookiebulls@gmail.com</a></p>
              </div>
               
            </div>

              {% include "main/_catergories.html"%}
            

            </div><!-- /.blog-sidebar -->


     </div>


       
     </div><!-- /.row -->

   </div><!-- /.container -->


{% endblock %}
 

app/templates/main/new_post.html
{% extends "layout.html" %}
{% import "bootstrap/wtf.html" as wtf%}
{% block post %}
<div class="container">


  <form method="POST">
  {{ form.hidden_tag() }}
      <div class="form-group">
        <label>{{form.title.label}}</label>
        {{form.title(class_="form-control")}}
      </div>

      <div class="form-group">
      <label>{{form.catergory.label}}</label>
         {{form.catergory(class_="form-control")}}
      </div>

      <div class="form-group">
        <label>{{form.content.label}}</label>
        {{form.content(class_="form-control", rows=10)}}
      </div>

      <div class="form-group">
      {{form.submit(class_="btn btn-default")}}
      </div>
  </form>




 
 
</div>
{% endblock %}